server:
  port: 80
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://github.com/notAvoiid,https://github.com/CeCamillo
file:
  upload-dir: /home/runner/work/recipes-back/uploadDir

spring:
  application:
    name: recipes-back
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recipes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo&createDatabaseIfNotExist=true
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  paths-to-match: /api/v1/**
  swagger-ui.use-root-path: true

