server:
  port: ${APPLICATION_PORT}
cors:
  originPatterns: http://localhost:${FRONTEND_PORT},http://localhost:${APPLICATION_PORT},https://github.com/notAvoiid,https://github.com/CeCamillo

spring:
  application:
    name: ${APPLICATION_NAME}
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: ${EXPIRATION_TIME}

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recipes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo&createDatabaseIfNotExist=true
    username: root
    password: admin123

  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  paths-to-match:
    - /api/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true
